# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ docker ]
  pull_request:
    branches: [ docker ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: START
      run: echo START

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: curl -sSL https://get.docker.com | sh
    
    - name: Install docker-compose
      run: curl -L https://get.daocloud.io/docker/compose/releases/download/1.22.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose

    - name: Clone Tiebaproject
      run: git clone https://gitee.com/ghosx/TiebaProject.git && cd TiebaProject
    
    - name: Run 
      run: docker-compose up
    
    - name: END
      run: END
